name: GCP Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        
    - name: Build and Push Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/sample-app:latest .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/sample-app:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/your-deployment your-container=gcr.io/${{ secrets.GCP_PROJECT_ID }}/sample-app:latest
