name: GCP App Engine Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: gcp-demo-project-415805
          export_default_credentials: true

      - name: Configure gcloud CLI
        run: gcloud config set project gcp-demo-project-415805

      - name: Create App Engine on GCP
        run: gcloud app create --region=us-east4

      - name: Deploy App Engine to GCP
        run: gcloud app deploy app.yaml --quiet
